### PR TITLE
Add fix for live video content sidebar being inverted

### PR DESCRIPTION
**Pull request by jordanpurinton**
Added selector for an issue where all the sidebar content in FB live videos were inverted.
Attached is a screenshot of the issue:
screen shot 2016-12-12 at 2 43 37 pm

### CODE REVIEW

**Comment by jordanpurinton** [comment]
I've also appended this fix with the selector for BBC.com's logo not showing up as outlined in issue #52 .
screen shot 2016-12-12 at 7 50 50 pm

**Comment by alexanderby** [comment]
Please, keep the alphabetical order by URL.

**Comment by jordanpurinton** [comment]
@alexanderby done

**Comment by jordanpurinton** [comment]
@alexanderby I also found an error with Twitter Summary card titles and content that I've added as well.

Screenshots:
screen shot 2016-12-13 at 9 20 08 am
screen shot 2016-12-13 at 9 19 51 am

**Comment by alexanderby** [comment]
Sorry that I haven't made a style guide, but for the next fix try to preserve whitespaces, like at other samples.

**Comment by jordanpurinton** [comment]
Will do, my bad. 
Also, it looks like that Twitter fix wound up inverting all images/videos on Twitter.
I've fixed this in my latest commit.

**Pull request merged**
