### PR TITLE
Fix Я.Музыка images

### PR DESCRIPTION
**Pull request by BANOnotIT**
Fix some images.

### CODE REVIEW

**Comment by BANOnotIT** [comment]
I have question: is `{common}` appended on all pages by default?

**Comment by BANOnotIT** [comment]
Oh... I checked. Yes it is.

**Comment by alexanderby** [comment]
Hi.

Common selectors are now added to every website. Common selectors were changed, please look if you still see an issue.

The contribution process was also changed https://github.com/alexanderby/darkreader#how-to-contribute

**Comment by alexanderby** [comment]
The issue should have been fixed.

**Pull request closed without merging**
