### PR TITLE
youtube subscription email preview images get inverted in gmail

### PR DESCRIPTION
**Pull request by Theyrealone**
fix youtube subscription emails incorrectly being inverted.
inverts table[background] the table[background] inversion must be before all the other inversions else it breaks the profile icon.

### CODE REVIEW

**Comment by alexanderby** [comment]
That sounds strange, "background" attribute is deprecated and was used in ancient browsers. Can I have a look on a page where wrong inversion it happens?

**Comment by Theyrealone** [comment]
image

**Comment by alexanderby** [comment]
I mean a hyperlink.

**Comment by Theyrealone** [comment]
I can forward you an email

**Comment by alexanderby** [comment]
You can forward it to darkreaderapp@gmail.com

**Comment by Theyrealone** [comment]
the image is a part of a table[class$=video-spotlight-width] that has the image as background

**Comment by alexanderby** [comment]
Great. That looks like a compatibility with some old mail agents. This problem affects not only GMail.

Lets add `[background]` (without table) to `invert` at `common` section (at new line after `[style*=background...]`) and `[background] *` to `noinvert` at `common` so that images inside will not be inverted twice.

**Comment by alexanderby** [comment]
Updating common fixes is always nervous :)

**Pull request merged**
