### PR TITLE
Fix card selectors

### PR DESCRIPTION
**Pull request by jordanpurinton**
More specified selectors, fixes issue where all images/videos are inverted on Twitter.

### CODE REVIEW

**Comment by jordanpurinton** [comment]
@alexanderby done.

**Comment by alexanderby** [comment]
I've just added `{common}` part, which reverts common selectors (images, iframes, videos etc.)

**Comment by jordanpurinton** [comment]
Gotcha. Sorry about the style differences, will keep that in mind for any future fixes.

**Comment by alexanderby** [comment]
Thanks for your contribution. I'm working on a new inversion engine and hope there will be no need in site-specific fixes.

**Pull request merged**
