### PR TITLE
Github header fix

### PR DESCRIPTION
**Pull request by unstope**
Added Github .Header element into invert list so that it inverts once more and becomes dark

### CODE REVIEW

**Comment by alexanderby** [comment]
Have a look at my latest fix for Facebook header. Chrome usually fails to render dynamic content that has filter applied multiple times (that was the case with Facebook, Linkedin etc). Maybe try to set Light color and dark text for the header via `"rules"`, invert (or not) the logo.

**Comment by unstope** [comment]
It works but after Chrome is restarted custom rules are not injected into the page. If I click Apply button they become injected till the next Chrome restart.

image

**Comment by RalphLesch** [comment]
That is already a known bug: #143

**Comment by unstope** [comment]
I have checked the behavior of first variant and it works the same way as the custom rules (until I restart Chrome). I guess these bugs are related to each other.

You can see how Github looks like before restart.

image

**Comment by alexanderby** [comment]
Profile icon get inverted. When you click on "+" near profile icon, the context menu gets partially disappeared. So, i would suggest to use background and color rules fix.

**Comment by alexanderby** [comment]
I've fixed the header by https://github.com/alexanderby/darkreader/commit/7a76fdc2cbade046c39c1917c8f6116cac25159b#diff-7d816c61670a7107b3850c13d1fa2861

**Pull request closed without merging**
