### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by thetric**

### CODE REVIEW

**Comment by alexanderby** [comment]
Great. But currently I'm refactoring the code, and all these files will be removed except `.gitignore`. But thanks for your effort. Did you fix these items automatically? I'm going to use TSLint to prevent such things in future.

**Comment by thetric** [comment]
Yeah, I have used IntelliJ for these changes.

Additionally to TSLint I recommend using https://github.com/prettier/prettier as a code formatter. Most IDEs/editors (Atom, VS Code, vim, IntelliJ/WebStorm,...) provide extensions for it. It also integrates nicely with TSLint.

**Comment by alexanderby** [comment]
This is a great tool, I will give it a try. I've also heard it can be executed before `git commit` https://medium.com/@brindelle/format-your-javascript-with-prettier-before-committing-177079ec356a

**Comment by thetric** [comment]
You can even configure this precommit hook in the package.json: https://prettier.io/docs/en/precommit.html

**Pull request merged**
